/* tslint:disable */
/* eslint-disable */
/**
 * Rails Reservation Api
 * Reservatin Api Document
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SignInResponseData,
    SignInResponseDataFromJSON,
    SignInResponseDataFromJSONTyped,
    SignInResponseDataToJSON,
} from './';

/**
 * 
 * @export
 * @interface SignInResponse
 */
export interface SignInResponse {
    /**
     * 
     * @type {SignInResponseData}
     * @memberof SignInResponse
     */
    data?: SignInResponseData;
}

export function SignInResponseFromJSON(json: any): SignInResponse {
    return SignInResponseFromJSONTyped(json, false);
}

export function SignInResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignInResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : SignInResponseDataFromJSON(json['data']),
    };
}

export function SignInResponseToJSON(value?: SignInResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': SignInResponseDataToJSON(value.data),
    };
}

