/* tslint:disable */
/* eslint-disable */
/**
 * Rails Reservation Api
 * Reservatin Api Document
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignInResponseData
 */
export interface SignInResponseData {
    /**
     * 
     * @type {string}
     * @memberof SignInResponseData
     */
    uid?: string;
    /**
     * 
     * @type {number}
     * @memberof SignInResponseData
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SignInResponseData
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof SignInResponseData
     */
    provider?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SignInResponseData
     */
    allowPasswordChange?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SignInResponseData
     */
    name?: string;
}

export function SignInResponseDataFromJSON(json: any): SignInResponseData {
    return SignInResponseDataFromJSONTyped(json, false);
}

export function SignInResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignInResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uid': !exists(json, 'uid') ? undefined : json['uid'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'provider': !exists(json, 'provider') ? undefined : json['provider'],
        'allowPasswordChange': !exists(json, 'allow_password_change') ? undefined : json['allow_password_change'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function SignInResponseDataToJSON(value?: SignInResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uid': value.uid,
        'id': value.id,
        'email': value.email,
        'provider': value.provider,
        'allow_password_change': value.allowPasswordChange,
        'name': value.name,
    };
}

