/* tslint:disable */
/* eslint-disable */
/**
 * Rails Reservation Api
 * Reservatin Api Document
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Reception,
    ReceptionFromJSON,
    ReceptionFromJSONTyped,
    ReceptionToJSON,
} from './';

/**
 * 
 * @export
 * @interface Receptions
 */
export interface Receptions {
    /**
     * 
     * @type {Array<Reception>}
     * @memberof Receptions
     */
    data?: Array<Reception>;
}

export function ReceptionsFromJSON(json: any): Receptions {
    return ReceptionsFromJSONTyped(json, false);
}

export function ReceptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Receptions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(ReceptionFromJSON)),
    };
}

export function ReceptionsToJSON(value?: Receptions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(ReceptionToJSON)),
    };
}

