/* tslint:disable */
/* eslint-disable */
/**
 * Rails Reservation Api
 * Reservatin Api Document
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Reservation
 */
export interface Reservation {
    /**
     * 
     * @type {number}
     * @memberof Reservation
     */
    reservationId: number;
    /**
     * 
     * @type {string}
     * @memberof Reservation
     */
    fpName?: string;
    /**
     * 
     * @type {Date}
     * @memberof Reservation
     */
    start?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Reservation
     */
    end?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof Reservation
     */
    reserved?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Reservation
     */
    canceled?: boolean;
}

export function ReservationFromJSON(json: any): Reservation {
    return ReservationFromJSONTyped(json, false);
}

export function ReservationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Reservation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reservationId': json['reservation_id'],
        'fpName': !exists(json, 'fp_name') ? undefined : json['fp_name'],
        'start': !exists(json, 'start') ? undefined : (new Date(json['start'])),
        'end': !exists(json, 'end') ? undefined : (new Date(json['end'])),
        'reserved': !exists(json, 'reserved') ? undefined : json['reserved'],
        'canceled': !exists(json, 'canceled') ? undefined : json['canceled'],
    };
}

export function ReservationToJSON(value?: Reservation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reservation_id': value.reservationId,
        'fp_name': value.fpName,
        'start': value.start === undefined ? undefined : (value.start.toISOString()),
        'end': value.end === undefined ? undefined : (value.end.toISOString()),
        'reserved': value.reserved,
        'canceled': value.canceled,
    };
}

