/* tslint:disable */
/* eslint-disable */
/**
 * Rails Reservation Api
 * Reservatin Api Document
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignUpResponseData
 */
export interface SignUpResponseData {
    /**
     * 
     * @type {string}
     * @memberof SignUpResponseData
     */
    uid?: string;
    /**
     * 
     * @type {number}
     * @memberof SignUpResponseData
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SignUpResponseData
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof SignUpResponseData
     */
    provider?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SignUpResponseData
     */
    allowPasswordChange?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SignUpResponseData
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof SignUpResponseData
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof SignUpResponseData
     */
    updatedAt?: Date;
}

export function SignUpResponseDataFromJSON(json: any): SignUpResponseData {
    return SignUpResponseDataFromJSONTyped(json, false);
}

export function SignUpResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignUpResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uid': !exists(json, 'uid') ? undefined : json['uid'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'provider': !exists(json, 'provider') ? undefined : json['provider'],
        'allowPasswordChange': !exists(json, 'allow_password_change') ? undefined : json['allow_password_change'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
        'updatedAt': !exists(json, 'updated_at') ? undefined : (new Date(json['updated_at'])),
    };
}

export function SignUpResponseDataToJSON(value?: SignUpResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uid': value.uid,
        'id': value.id,
        'email': value.email,
        'provider': value.provider,
        'allow_password_change': value.allowPasswordChange,
        'name': value.name,
        'created_at': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updated_at': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

