/* tslint:disable */
/* eslint-disable */
/**
 * Rails Reservation Api
 * Reservatin Api Document
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignOutRequest
 */
export interface SignOutRequest {
    /**
     * email
     * @type {string}
     * @memberof SignOutRequest
     */
    email?: string;
    /**
     * acccess token
     * @type {string}
     * @memberof SignOutRequest
     */
    accessToken?: string;
    /**
     * client
     * @type {string}
     * @memberof SignOutRequest
     */
    client?: string;
}

export function SignOutRequestFromJSON(json: any): SignOutRequest {
    return SignOutRequestFromJSONTyped(json, false);
}

export function SignOutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignOutRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
        'accessToken': !exists(json, 'access-token') ? undefined : json['access-token'],
        'client': !exists(json, 'client') ? undefined : json['client'],
    };
}

export function SignOutRequestToJSON(value?: SignOutRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'access-token': value.accessToken,
        'client': value.client,
    };
}

